<!DOCTYPE html>
<HTML>
<HEAD>
<meta http-equiv="Content-type" content="text/html; charset=windows-1251" />
<LINK REL="stylesheet" HREF="main_n1.css" TYPE="text/css">
</HEAD>
<DIV>
<DIV ID="cheader" align=center>
<table>
 <tr>
 <td>
 <img src="logo_v.gif" width="120" height="60">
 </td>
 <td>
 <h2 align="center"><font face="verdana" color="#006699">ФГУП "Всероссийский научно исследовательский институт автоматики им. Н.Л.Духова"</font></h1>
 </td>
 </tr>
 </table>
</DIV>
<DIV ID="cnavbar">
<UL>
<LI><A href="/index.htm"><b><font size="5">Блок регистрации</font></b></a></L1>
<LI><a href="/parametr.cgi"><b><font size="5">Параметры блока регистрации</font></b></a></L1>
<UL>
<LI><a href="../dir_set.cgi">АЧХ и ЦНРК блока регистрации</a></CODE></LI>
<LI><a href="../dir_set_kan.cgi">АЧХ и ЦНРК канала</a></CODE></LI>
<LI><a href="/parametr_sb.cgi">Параметры сейсмоприемников</a></CODE></LI>
</UL>
</LI>
<LI><a href="/command.cgi"><b><font size="5">Команды</font></b></a></L1>
<UL>
<LI><a href="../clb.cgi">Контроль</a></CODE></LI>
<LI><a href="../meteo.cgi">Метеоданные</a></CODE></LI>
<LI><a href="/dir.cgi">Память</a></CODE></LI>
</UL>
</LI>
<LI><a href="/gps.cgi"><b><font size="5">СЕВ</font></b></a></L1>
<UL>
<LI><a href="../picklist.cgi">Настройки</a></CODE></LI>
</UL>
</LI>
<LI><a href="/buttons.cgi"><b><font size="5">Входы</font></b></a></L1>
<LI><a href="/network.cgi"><b><font size="5">Сеть</font></b></a></L1>
</UL>
</DIV>
<td colSpan=5 height=380 width="815" vAlign=top background="llblue.jpg" style="background-repeat: repeat-y;">
<DIV ID="cmain">
<table width="90%" border=0 align=center>
      <tbody><tr>
       <td width="95%">


